default_platform(:android)

platform :android do
  desc "Build and distribute APK to Firebase"
  lane :deploy_firebase do
    flavor = ENV["FLAVOR"] || "product" # Lấy từ biến môi trường, mặc định là "product"
    UI.message "🚀 Building flavor: #{flavor}" # Kiểm tra giá trị FLAVOR


    apk_path = "../build/app/outputs/apk/#{flavor}/release/app-#{flavor}-release.apk"

    firebase_app_distribution(
      app: "1:212347360763:android:3f0583c2edb094672ee75e",
      android_artifact_type: "APK",
      android_artifact_path: apk_path,
      groups: "test",
      release_notes: "Release notes for this #{flavor} build",
      firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
end
