platform :android do
  desc "Build and distribute APK to Firebase"
  lane :deploy_firebase do |options|
    flavor = options[:flavor] || "product"
    UI.message "🚀 Building flavor: #{flavor}" # In ra để kiểm tra
    env_file = ".env.#{flavor}"
    
    gradle(
      task: "assemble#{flavor.capitalize}Release",
      properties: {
        "target": "lib/main_#{flavor}.dart",
        "envFile": env_file,
        "flavor": flavor
      }
    )

    apk_path = "../build/app/outputs/apk/#{flavor}/release/app-#{flavor}-release.apk"

    firebase_app_distribution(
      app: "1:212347360763:android:3f0583c2edb094672ee75e",
      android_artifact_type: "APK",
      android_artifact_path: apk_path,
      groups: "test",
      release_notes: "Release notes for this #{flavor} build",
      firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
end
