name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0  # Chọn phiên bản Flutter phù hợp với dự án của bạn

      - name: Install dependencies
        run: flutter pub get
      
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Install Fastlane
        run: gem install fastlane --user-install

      - name: Install Fastlane Plugin for Firebase
        run: |
          export GEM_HOME="$HOME/.gem"
          export PATH="$GEM_HOME/bin:$PATH"
          gem install fastlane-plugin-firebase_app_distribution --user-install


      - name: Set Firebase CLI Token
        run: echo "${{ secrets.FIREBASE_TOKEN }}" > "$HOME/.firebase_token"
      
      - name: Create signing folder
        run: mkdir -p android/app/signing/

      - name: Decode Keystore
        run: |
          echo -n "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/signing/release_key.jks

      - name: Decode key.properties
        run: |
          echo -n "${{ secrets.KEY_PROPERTIES_BASE64 }}" | base64 --decode > android/key.properties

      - name: Build APK for Product Flavor
        run: flutter build apk --release --flavor product --target=lib/main_product.dart

      - name: List APK files (Debugging)
        run: ls -lah build/app/outputs/apk/product/release/

      - name: Deploy to Firebase using Fastlane
        run: cd android && fastlane android deploy_firebase
